use anchor_lang::prelude::*;

pub type VortexDexResult<T = ()> = std::result::Result<T, DexError>;

#[error_code]
#[derive(PartialEq, Eq)]
pub enum DexError {
    #[msg("Not approved")]
    NotApproved,
    /// The owner of the input isn't set to the program address generated by the
    /// program.
    #[msg("Input account owner is not the program address")]
    InvalidOwner,
    /// The input token account is empty.
    #[msg("Input token account empty")]
    EmptySupply,
    /// The input token is invalid for swap.
    #[msg("InvalidInput")]
    InvalidInput,
    /// Address of the provided pool token mint is incorrect
    #[msg("Address of the provided lp token mint is incorrect")]
    IncorrectLpMint,
    /// Exceeds desired slippage limit
    #[msg("Exceeds desired slippage limit")]
    ExceededSlippage,
    /// Given pool token amount results in zero trading tokens
    #[msg("Given pool token amount results in zero trading tokens")]
    ZeroTradingTokens,
    #[msg("Not support token_2022 mint extension")]
    NotSupportMint,
    #[msg("invaild vault")]
    InvalidVault,
    #[msg("Init lp amount is too less(Because 100 amount lp will be locked)")]
    InitLpAmountTooLess,
    #[msg("Already Made a Bet on the game")]
    AlreadyMadeABetOnGame,
    #[msg("Bet Type cannot be changed")]
    UserHasDifferentBetType,
    #[msg("You lost the bet. No amount will be rewarded")]
    UserLostTheBet,
    #[msg("Failed Unwrap")]
    FailedUnwrap,
    #[msg("Unable to load AccountLoader")]
    UnableToLoadAccountLoader,
    #[msg("DefaultError")]
    DefaultError,
    #[msg("InvalidPDASigner")]
    InvalidPDASigner,
    #[msg("InvalidPDA")]
    InvalidPDA,
    #[msg("Error During Math Computation")]
    MathError,
}

#[macro_export]
macro_rules! print_error {
    ($err:expr) => {{
        || {
            let error_code: DexError = $err;
            msg!("{:?} thrown at {}:{}", error_code, file!(), line!());
            $err
        }
    }};
}