[package]
name = "vortex-contracts"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021" 

[lib]
crate-type = ["cdylib", "lib"]
name = "vortex_contracts"
path="src/lib.rs"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
enable-log = []
devnet = []
client = []


[dependencies]
anchor-lang = "0.28.0"
solana-program = "1.16"
anchor-spl = "0.28.0"
bytemuck = { version = "1.4.0" }
borsh = "0.10.3"
num-traits = "0.2"
uint = { version = "0.9.1", default-features = false }
num-derive = "0.3"
arrayref = "0.3.6"
solana-security-txt = "1.1.0"
